---
title: Menicucci & Associati
timezone: Europe/Rome
collections:
  docs:
    title: Docs
    output: true
    permalink: "/:collection/:path/"
  portfolio:
    title: Portfolio
    output: true
    permalink: "/:collection/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: false
- scope:
    path: ''
    type: portfolio
  values:
    layout: single
    author_profile: false
    share: true
url: http://www.menicucci.co
baseurl: 
locale: it
title_separator: "/"
name: Brunello Menicucci
description: Crescere in Modo Sostenibile e Profittevole
claim: Crescere in Modo Sostenibile e Profittevole
teaser: 
breadcrumbs: true
words_per_minute: 200
comments:
  provider: disqus
  disqus:
    shortname: menicucciassociati
google_site_verification: oxQ9XiBjxU9U4BqyAReldUAQFfVdt7G0sDXfMbnEZRc
twitter:
  username: bmenicucci
social:
  type: 
  name: 
  links:
  - name: twitter
    url: https://twitter.com/bmenicucci
  - name: linkedin
    url: https://it.linkedin.com/in/bmenicucci
  - name: google_plus
    url: https://plus.google.com/+BrunelloMenicucciCMC
analytics:
  provider: google-universal
  google:
    tracking_id: UA-29374310-1
author:
  name: Brunello Menicucci
  avatar: bio-photo.jpg
  bio: Management Consultant CMC™
  location: Lido di Camaiore, LU
  email: brunello@menicucci.co
  flickr: 
  google_plus: BrunelloMenicucciCMC
  linkedin: bmenicucci
  skype: skype:brunello.menicucci?chat
  twitter: bmenicucci
  youtube: 
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
category_archive:
  type: jekyll-archives
  path: "/categories/"
tag_archive:
  type: jekyll-archives
  path: "/tags/"
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
markdown: kramdown
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
include:
- ".htaccess"
- _pages
- _plugins
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
- gensite
- servesite
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
compress_html:
  clippings: all
  ignore:
    envs: development
